server:
  port: 8082
  error:
    whitelabel:
      enabled: false # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
spring:
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      database: subscription
      uri: mongodb://localhost:27017
#eureka:
#  client:
#    service-url: 
#      default-zone: http://localhost:1111
  application:
    name: SUBSCRIPTION-SERVICE

logging:
  file:
    name: C:/microservices_logs/services.log